name: Python application

on:
  push:
    branches:
      - 'master'
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test
      env:
        TEST_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBTOKEN }}
      run: |
        echo ${#TEST_GITHUB_TOKEN}
        echo ${{ secrets.DOCKERHUBUSER }}
        echo ${{ secrets.DOCKERHUBTOKEN }}
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./python/requirements.txt
        
    -
      name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    -
      name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUBUSER }}
        password: ${{ secrets.DOCKERHUBTOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        context: ./python
        push: true
        tags: ${{ secrets.DOCKERHUBUSER }}/acg-training:hellov1.0
